Create feeder subsystem
team4099/InfiniteRecharge-2020 pull request #15
Opened 2020-01-08 21:27 UTC by rbhog

Resolves #14

2020-01-08 23:53 UTC, aidangoettsch requested changes

2020-01-08 23:53 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    private fun setFeederInPower(power: Double) {
make this a setter on the actual var

2020-01-08 23:53 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        inMasterTalon = CTREMotorControllerFactory.createDefaultTalon(Constants.Feeder.FEEDER_IN_MASTER_TALON_ID)
can combine declaration and initialization

2020-01-08 23:53 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        synchronized(this@Feeder) {
can do `@Synchronized` because this is actually feeder here (this is why subsystem implementing loop makes so much sense)

2020-01-08 23:53 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +                    setFeederOutPower(-0.5)
may want to move this to Constants

2020-01-08 23:54 UTC, aidangoettsch commented
also you have minor style issues that detekt caught plz fix

MagicNumber can either be suppressed or moved to constants

2020-01-09 13:13 UTC, aidangoettsch requested changes

2020-01-09 13:13 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        synchronized(this) {
don't need this with the synchronized annotation

2020-01-09 13:13 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
>      override fun outputTelemetry() { }
should add state atl to smartdashboard

2020-01-09 23:08 UTC, atzho commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    enum class FeederState {
should have an idle state

2020-01-17 20:51 UTC, ktorsh commented on src/main/kotlin/com/team4099/robot2020/config/Constants.kt
> +        const val FEEDER_HOLD_POWER = 0.5
I feel like hold power should be less than 0.5, do like 0.1

2020-01-18 14:54 UTC, atzho approved these changes
Yes

2020-01-18 14:59 UTC, aidangoettsch commented
wait plz to add helixlogger

2020-01-21 22:14 UTC, rbhog commented on InfiniteRecharge-2020.iml
> +</module>
change your gradle settings in IntelliJ to get rid of this

2020-01-21 22:16 UTC, rbhog commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    enum class FeederState {
^

2020-01-21 22:16 UTC, rbhog commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    override fun registerLogging() { }
add helix logger stuff

2020-01-21 22:16 UTC, rbhog commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        feederState = FeederState.HOLD
shouldn't this be idle not holding for onStart and onStop?

2020-01-25 18:47 UTC, plusparth submitted a review, later dismissed
Overall, needs usage of break beam sensors (digital inputs) and the other minor changes

2020-01-25 18:47 UTC, plato2000 commented on InfiniteRecharge-2020.iml
> +<?xml version="1.0" encoding="UTF-8"?>
pls to delete project files

2020-01-25 18:47 UTC, plato2000 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    private val inMasterTalon = CTREMotorControllerFactory.createDefaultTalonSRX(Constants.Feeder.FEEDER_IN_MASTER_ID)
two motor controllers should be SPARK MAX, the top one (what you call the "out" one) should be a Talon SRX

2020-01-25 18:47 UTC, plato2000 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        inSlaveVictor.inverted = true
use the setInverted method that takes an enum (so you can specify inversion relative to master)

2020-01-25 18:47 UTC, plato2000 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    enum class FeederState {
should have an exhaust state (to dump)

2020-01-25 18:47 UTC, plato2000 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        HelixLogger.addSource("Feeder master motor power") { inMasterTalon.motorOutputVoltage }
Follow standards for capitalization of the source names (eg. "Feeder Master Motor Power")

2020-01-25 18:47 UTC, plato2000 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        HelixLogger.addSource("Feeder out motor power") { outSparkMax.outputCurrent }
can we rename this (in all places) to stopper wheel or something

2020-02-01 00:00 UTC, aidangoettsch requested changes

2020-02-01 00:00 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/lib/motorcontroller/SparkMaxControllerFactory.kt
> +    fun createPermanentSlaveSparkMax(id: Int, master: LazySparkMax, invertToMaster: Boolean = false): LazySparkMax {
plz make this just a CANSparkMax because lazy extends it anyway

2020-02-01 00:00 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    private val stopperTalon = CTREMotorControllerFactory.createDefaultTalonFX(Constants.Feeder.FEEDER_OUT_ID)
this isn't going to be a talon fx, will probably be an srx

2020-02-01 00:00 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +                HelixEvents.addEvent("FEEDER", "state changed to $value")
need to assign backing field (`field = value`)

2020-02-01 00:00 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +    override fun zeroSensors() { }
should reset neo encoder position

2020-02-01 00:01 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +        inMasterSparkMax.setInverted(false)
why is inverted set here if we set it in the factory

2020-02-01 00:01 UTC, aidangoettsch commented on src/main/kotlin/com/team4099/robot2020/subsystems/Feeder.kt
> +            invertToMaster = true
don't need to specify argument name here

2020-02-01 01:12 UTC, aidangoettsch approved these changes

2020-02-01 01:15 UTC, merged