Feature/drive
team4099/InfiniteRecharge-2020 pull request #37
Opened 2020-01-30 21:47 UTC by jazon-liu

2020-01-30 22:55 UTC, azhong2002 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Drive.kt
> +        rightMasterTalon.set(ControlMode.PercentOutput, right, DemandType.ArbitraryFeedForward, 0.0)
This us more of a workaround than a fix, make sure the setter in lazytalon works instead

2020-01-30 22:55 UTC, azhong2002 commented on src/main/kotlin/com/team4099/robot2020/Robot.kt
> +            autoModeExecuter = AutoModeExecuter(DriveForwardMode(0.0))
Should go back to dashboardconfig selected mode

2020-01-31 20:58 UTC, rbhog approved these changes
Nice job??

2020-01-31 22:48 UTC, atzho requested changes

2020-01-31 22:48 UTC, azhong2002 commented on src/main/kotlin/com/team4099/robot2020/subsystems/Drive.kt
> +        leftMasterTalon.set(ControlMode.MotionMagic, metersToNative(leftMeters), DemandType.ArbitraryFeedForward, 0.0)
Use actual fix pls i am adding so review get angwy

2020-02-04 21:21 UTC, rbhog approved these changes
Nice Job!

2020-02-04 21:26 UTC, merged